[package]
name = "sneaky-mouse-server"
version = "0.1.0"
edition = "2021"


[dependencies]
rand_pcg = "*"
rand = "*"
chrono = "*"

[dependencies.redis]
version = "*"
features = ["streams"]

[[bin]]
name = "sm-server"
path = "src/main.rs"
[[bin]]
name = "dummy"
path = "src/dummy.rs"
